# Generated by Django 5.2.7 on 2025-10-10 20:14

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_url", models.URLField(max_length=500)),
                ("secret", models.CharField(default=secrets.token_hex, max_length=128)),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of event names that trigger the webhook.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_subscriptions",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("company", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["status"], name="webhooks_we_status_131087_idx"
                    ),
                    models.Index(
                        fields=["company", "status"],
                        name="webhooks_we_company_f6bc69_idx",
                    ),
                ],
            },
        ),
    ]
