# Generated by Django 5.0.6 on 2025-10-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_type", models.CharField(max_length=64)),
                ("reference_id", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["node_type", "reference_id"],
                        name="graph_graph_node_ty_57ebc4_idx",
                    )
                ],
                "unique_together": {("node_type", "reference_id")},
            },
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(max_length=64)),
                ("weight", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="graph.graphnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="graph.graphnode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "relation_type"],
                        name="graph_graph_source__5c3a07_idx",
                    ),
                    models.Index(
                        fields=["target", "relation_type"],
                        name="graph_graph_target__c779e4_idx",
                    ),
                ],
                "unique_together": {("source", "target", "relation_type")},
            },
        ),
    ]
