# Generated by Django 5.2.7 on 2025-10-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="graphnode",
            name="graph_graph_node_ty_57ebc4_idx",
        ),
    ]
