# Generated by Django 5.2.7 on 2025-10-10 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryCondensationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("scheduled_for", "created_at"),
            },
        ),
        migrations.RenameIndex(
            model_name="memoryentry",
            new_name="memory_memo_sensiti_619c6c_idx",
            old_name="memory_memo_sensiti_4f9d62_idx",
        ),
        migrations.RenameIndex(
            model_name="memoryentry",
            new_name="memory_memo_entry_t_f93e58_idx",
            old_name="memory_memo_entry_t_dcf4c1_idx",
        ),
        migrations.AddField(
            model_name="memorycondensationjob",
            name="memory_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condensation_jobs",
                to="memory.memoryentry",
            ),
        ),
        migrations.AddIndex(
            model_name="memorycondensationjob",
            index=models.Index(
                fields=["status", "scheduled_for"], name="memory_memo_status_173637_idx"
            ),
        ),
    ]
