# Generated by Django 5.2.7 on 2025-10-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embeddings", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="embedding",
            new_name="embeddings__model_n_129096_idx",
            old_name="embeddings_model_name_8755f4_idx",
        ),
    ]
