# Generated by Django 5.2.7 on 2025-10-10 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_identifier",
                    models.CharField(
                        help_text="Stable identifier of the agent or client receiving access.",
                        max_length=255,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Granted scopes such as memory.read or memory.write.",
                    ),
                ),
                (
                    "sensitivity_levels",
                    models.JSONField(
                        default=list,
                        help_text="List of sensitivity levels that the agent is allowed to access.",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "agent_identifier", "status"],
                        name="consents_co_user_id_48fc93_idx",
                    )
                ],
                "unique_together": {("user", "agent_identifier", "version")},
            },
        ),
    ]
