# Generated by Django 5.2.7 on 2025-10-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_app_lab_a84053_idx",
            old_name="audit_audit_app_lab_9872a2_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_timesta_19e18a_idx",
            old_name="audit_audit_timesta_e86f3e_idx",
        ),
    ]
